### PR TITLE
add autonomous constants

### PR DESCRIPTION
**Pull request by EwanKannolt**

### CODE REVIEW

**Review by KSatsujin — APPROVED** [review]
It looks pretty good to me, although I'm still not so sure about that trigger angle. We can pay more attention to that in tuning, though.

**Comment by EwanKannolt** [comment]
Yeah, we'll have to change it in the future, we just did that because we were cramped with the amount of time that we had left.

**Comment by EwanKannolt** [comment]
Should I merge it right now?

**Comment by EwanKannolt** [comment]
I'm just going to merge it because you approved it.

**Pull request merged**
