### PR TITLE
Added simgui things to .gitignore

### PR DESCRIPTION
**Pull request by KSatsujin**

### CODE REVIEW

**Comment by shanealv** [comment]
You can also remove the files that you add to the `.gitignore`, or otherwise they will still be there. Just keep in mind that certain elements may no longer show up by default if those files are removed.

**Comment by KSatsujin** [comment]
The problem with removing them entirely is that you would be starting with a blank slate on the sim window, and they would just be re-created by running the simulator.

**Comment by shanealv** [comment]
> The problem with removing them entirely is that you would be starting with a blank slate on the sim window, and they would just be re-created by running the simulator.

K, if you plan to keep them, then just be aware that to update the sim-gui files you need to `git add --force` them manually from now on.

**Review by shanealv — APPROVED** [review]

**Comment by KSatsujin** [comment]
That's fine.

**Pull request merged**
